# Write your MySQL query statement below
SELECT
 PLAYER_ID,
 EVENT_DATE,
 SUM(GAMES_PLAYED) OVER(PARTITION BY PLAYER_ID ORDER BY EVENT_DATE ROWS BETWEEN UNBOUNDED PRECEEDING AND CURRENT ROW) AS GAMES_PLAYED_SO_FAR
FROM ACTIVITY
ORDER BY 1,2